CREATE OR REPLACE TRIGGER T1
BEFORE UPDATE OF SALARY ON EMP
FOR EACH ROW
BEGIN
INSERT INTO TARGET(OLDEMPNO,OLDSALARY,NEWSALARY,COL4,USERNAME)VALUES(:OLD.EMPLOYEE_ID,:OLD.SALARY,:NEW.SALARY,SYSDATE,USER);
END;

